<h1>Test Entity Generator</h1>
<p>generating...</p>

<cfscript>
    TEMPLATE_FILE = "models/_template.cfc.txt";
    
    start = getTickCount();
    source = fileRead( TEMPLATE_FILE );
    for( i = 1; i <= 1000; i++ ){
        fileWrite( "models/autogenerated/TestEntity#i#.cfc", source );
    }
    end = getTickCount();
</cfscript>
<cfoutput>
<p>
    Finished in <strong>#end-start#ms</strong>.
</p>
</cfoutput>